### ISSUE TITLE
When opening an issue in this repo, there are two steps to get to a blank issue. 

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zecwallet-lite#10]
The first step is a click-through to _not_ open a templated bug report. The second step is to remove a somewhat rude autogenerated text message that reads 
"<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>"

I think we should consider changing this setup or at least make the second warning more polite.

**Comment by AloeareV** [comment]
I'm not sure that the bug report template is especially useful.. Should we just remove all templates? I don't see a way to configure a blank issue, I think that warning message is procedurally generated based off of what templates exist, but I could spin up an 'Other' template easily enough.

**Comment by dannasessha** [comment]
The change that removed `.github/ISSUE_TEMPLATE/issue_template.md` ( #20 ) seemed to remove the click-through on github to get to an issue without a warning, but did not remove the templated warning in an issue: that is, the newly opened issue is not blank.

**Comment by AloeareV** [comment]
> I'm not sure that the bug report template is especially useful.. Should we just remove all templates? I don't see a way to configure a blank issue, I think that warning message is procedurally generated based off of what templates exist, but I could spin up an 'Other' template easily enough.

Looks like I was wrong, and they can be configured separately. Now that we know this, I'm a bit more enthusiastic about adding the bug report template back, although not necessarily before we have more than just one template we want.
