### ISSUE TITLE
dev branch "yarn build" still building with adityapk00 packages 

### ISSUE THREAD

**Issue by Gunnar-Stunnar** [zingolabs/zecwallet-lite#13]
**Describe the bug**
Dev branch rust build is still pointing to adityapk00 content

`Compiling zcash_primitives v0.5.0 (https://github.com/adityapk00/librustzcash?rev=adeb3ec4ad15480482bc2962bc9fe453814db9ee#adeb3ec4)`

`   Compiling zcash_proofs v0.5.0 (https://github.com/adityapk00/librustzcash?rev=adeb3ec4ad15480482bc2962bc9fe453814db9ee#adeb3ec4)`

`Compiling zecwalletlitelib v0.1.0 (https://github.com/adityapk00/zecwallet-light-cli?rev=89be353b5ea600ee21d998254598fb19d8778417#89be353b)`

`   Compiling zcash_client_backend v0.5.0 (https://github.com/adityapk00/librustzcash?rev=adeb3ec4ad15480482bc2962bc9fe453814db9ee#adeb3ec4)`

`Compiling equihash v0.1.0 (https://github.com/adityapk00/librustzcash?rev=adeb3ec4ad15480482bc2962bc9fe453814db9ee#adeb3ec4)`

**To Reproduce**
1. run `yarn build` after `yarn install`

**Expected behavior**
pointing at Zingolabs repositories, not adityapk00

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Nill
 - Local compile

**Comment by dannasessha** [comment]
This was fixed by #24 - Thank you @Gunnar-Stunnar !
