### ISSUE TITLE
App launch obscures the UI with an error message.

### ISSUE THREAD

**Issue by zancas** [zingolabs/zecwallet-lite#5]
![zwl_launch](https://user-images.githubusercontent.com/640955/169933334-03d47920-8567-4b29-b3cf-328c42d67085.png)

**Comment by dannasessha** [comment]
This doesn't happen for me on your #7 PR branch! So that may "fix" this issue, at least as far as the 'popup' error page goes.

**Comment by zancas** [comment]
Fixed.
